export const IPC = {
  CONFIG_GET: 'config:get',
  CONFIG_SET: 'config:set',
  CONFIG_RESET: 'config:reset',
  CONFIG_PATH: 'config:path',
  FS_IS_DIR: 'fs:is-directory',
  FS_IS_EMPTY: 'fs:is-empty',
  FS_MOVE_VAULT: 'fs:move-vault',
  PICK_FOLDER: 'dialog:pick-folder',
  BRAIN_SWAP: 'brain:swap',
  LOG_PUSH: 'log:push',
  LOG_BUFFER: 'log:buffer',
  STAT_ENTRIES: 'stat:entries',
  STAT_ISSUES: 'stat:issues',
  STAT_FIELDS: 'stat:fields',
  STAT_PROJECTS: 'stat:projects',
  STAT_STATUS: 'stat:status',
  STAT_GET: 'stat:get',
  MCP_STATUS: 'mcp:status',
  MCP_REGISTER: 'mcp:register',
  MCP_UNREGISTER: 'mcp:unregister',
}
